{% set name = "xarray-beam" %}
{% set version = "0.6.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/xarray-beam-{{ version }}.tar.gz
  sha256: 5a48a4693329d43287beb1f4bc118b03b133624cad4eaf11210017a1b8dd9e48

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - apache-beam >=2.31.0
    - dask-core
    - immutabledict
    - python >={{ python_min }}
    - rechunker >=0.5.1
    - xarray
    - zarr

test:
  imports:
    - xarray_beam
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/google/xarray-beam
  summary: Distributed Xarray with Apache Beam
  description: Xarray-Beam is a Python library for building Apache Beam pipelines with Xarray datasets
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maxrjones
